#+Title: Orgmode templates for Latex PDF export

This repository contains =Orgmode= article templates to be exported in latex - PDF. The templates try to follow as much as possible the Latex templates provided by the publishers.
These templates can be used to write scientific articles in =Orgmode= and then export documents ready for submissions.
* Wiley-Chemistry template
The [[https://github.com/ajgiuliani/orgmode-templates/blob/main/WileyChemistry-template/paper.org][paper.org]] is the =orgmode= template.
The Latex templates may be downloaded from here: https://onlinelibrary.wiley.com/page/journal/15213773/homepage/authors
The `.eps` Wiley-VCH logo had to be exported to pdf to be inserted in the templates.

The following Emacs settings are used for this template.
#+begin_src elisp
  (add-to-list ' org-latex-classes
  	       '("wiley-chemistry"
                   "\\documentclass{WileyChemistry-template}"
                  ("\\section{%s}" . "\\section*{%s}")
                  ("\\subsection{%s}" . "\\subsection*{%s}")
                  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                  ("\\paragraph{%s}" . "\\paragraph*{%s}")
                  ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (setq org-latex-pdf-process
  	'("pdflatex -interaction nonstopmode %f"
          "bibtex %b"
          "pdflatex -interaction nonstopmode %f"
          "pdflatex -interaction nonstopmode %f"))
  
#+end_src
* ACS template
The =orgmode= paper template for ACS article is given in the [[https://github.com/ajgiuliani/orgmode-templates/blob/main/ACS-template/paper.org][paper.org]]. I relies on the Latex ACS template available here: https://pubs.acs.org/page/4authors/submission/tex.html.
Reference formatting is done using biblatex with the biber backend together with the the achemso package. The following settings are used for this template.
#+begin_src elisp
  (add-to-list ' org-latex-classes
           '("ACS-article"
             "\\documentclass[letterpaper]{article}
              \\usepackage{achemso}
              \\usepackage{geometry}
              \\geometry{margin = 1in}
              \\usepackage{setspace}
              \\usepackage{float}
              \\newfloat{scheme}{htbp}{los}
              \\floatname{scheme}{Scheme}
              \\floatname{chart}{Chart}
              \\newfloat{graph}{htbp}{loh}
              \\usepackage[version = 4]{mhchem}
              \\setcounter{secnumdepth}{-1}
              \\usepackage{authblk}"
             ("\\section{%s}" . "\\section*{%s}")
             ("\\subsection{%s}" . "\\subsection*{%s}")
             ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
             ("\\paragraph{%s}" . "\\paragraph*{%s}")
             ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

#+end_src
The =org-latex-pdf-process= settings:
#+begin_src elisp
  (setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "biber %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))  
        #+end_src
have been placed in the template paper as =elisp= code block with =:exports none=. It is a flexible solution, since these settings can be adjusted for every template if necessary.
The pdf file produced [[https://github.com/ajgiuliani/orgmode-templates/blob/main/ACS-template/paper.pdf][paper.pdf]] is almost identical as the one available from the ACS website.
