#+Title: acs-orgmode-template
#+LATEX_CLASS: ACS-article
#+LANG: en
#+OPTIONS: toc:nil date:nil author:nil H:4 num:2 Tex:t LaTex:t title:nil
#+OPTIONS: tags:nil timestamp:t todo:nil stat:t num:nil
#+OPTIONS: tex:t
#+EXPORT_EXCLUDE_TAGS: noexport

#+latex_header: \usepackage[backend=biber,style=chem-acs]{biblatex}

#+latex_header: \addbibresource{references.bib}

#+latex: \doublespacing

#+latex: \author[1]{Andrew N. Other}
#+latex: \author[1]{Fred T. Secondauthor}
#+latex: \author[1]{I. Ken Groupleader*}
#+latex: \affil[1]{Department of Chemistry, Unknown University, Unknown Town}
#+latex: \author[2]{Susanne K. Laborator}
#+latex: \affil[2]{Lead Discovery, BigPharma, Big Town, USA}
#+latex: \author[1]{Kay T. Finally}

#+latex: \title{\textbf{A ``template'' model document for submission to the American Chemical Society (ACS)}}

#+latex: % Use the \date command for email address(s) of corresponding authors
#+latex: \date{*Email: i.k.groupleader@unknown.uu}


#+latex: \maketitle

#+begin_src elisp :exports none 
  (setq org-latex-pdf-process
      '("latexmk -pdflatex='pdflatex -interaction nonstopmode' -pdf -bibtex -f %f"))
  (setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "biber %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))  
        #+end_src

        #+RESULTS:
        | pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f | biber %b | pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f |


#+begin_src latex

  \begin{abstract}
    This is an example document for creating \LaTeX{} submissions to the American
    Chemical Society (ACS) for publication. As ACS does not use \LaTeX{} for
    typesetting accepted manuscripts, this template does not seek to
    reproduce the appearance of a published paper.
  \end{abstract}
  
        #+end_src


* Keywords
Some journals require keywords: these normally should be given immediately
after the abstract.

* Abbreviations
Some journals require a list of abbreviations: these normally should be given
immediately after the keyswords (if required).

* Introduction
This is a paragraph of text to fill the introduction of the demonstration file.
* Results and Discussion
** Outline
The document layout should follow the style of the journal concerned. Where
appropriate, sections and subsections should be added in the normal way.

** References
References should be given in the normal way in \LaTeX{}. If you are using
\textsf{biblatex} (as recommended) then you can use the full range of citation
commands it provides. If you choose to use classical Bib\TeX{},\autocite{article1,article2,WEB,bookvolume,CCDC} the
\textsf{natbib} package will be loaded and you can use it's commands \autocite{book,article3}.

** Floats
New float types are set up in the preamble. The means graphics are included as
follows (Scheme \ref{sch:example} or [[sch:example]]). As illustrated, the float is ``here'' if
possible.

#+NAME: sch:example
#+CAPTION: An example scheme
  \begin{scheme}
    \begin{center}

    Your scheme graphic would go here: \texttt{.eps} format\\
    for \LaTeX\, or \texttt{.pdf} (or \texttt{.png}) for pdf\LaTeX\\
    \textsc{ChemDraw} files are best saved as \texttt{.eps} files:\\
    these can be scaled without loss of quality, and can be\\
    converted to \texttt{.pdf} files easily using \texttt{eps2pdf}.\\
    
    %\includegraphics{graphic}

    \end{center}
  \end{scheme}


A standard figure environment: Fig. [[fig-example]].

#+CAPTION: Caption
#+NAME: fig-example
#+ATTR_LATEX: :width 8.6cm
[[file:fig.pdf]]

The use of the different floating environments is not required, but it is intended to make document preparation easier for authors. In general, you should place your graphics where they make logical sense; the production process will move them if needed.

** Math
If packages such as \textsf{amsmath} are required, they should be loaded in the
preamble. However, the basic \LaTeX math(s) input should work correctly
without this. Some inline material $1 + 1 = 2$ followed by some display. \[ A =
\pi r^2 \]

It is possible to label equations in the usual way (Eq. \ref{eqn:example} or Eq. [[eqn:example]]). Note that if using a code block, then the =\label{}= is mandatory for the reference to work.

#+NAME: eqn:example
#+begin_src latex
  \begin{equation}
    \frac{\mathrm{d}}{\mathrm{d}x} \, r^2 = 2r
    \label{eqn:example}
  \end{equation}  
#+end_src

This can also be used to have equations containing graphical content. To align
  the equation number with the middle of the graphic, rather than the bottom, a
  minipage may be used, such as in equation [[eqn:graphic]].

#+NAME: eqn:graphic
  \begin{equation}
     \begin{minipage}[c]{0.80\linewidth}
      \centering
      As illustrated here, the width of \\
      the minipage needs to allow some  \\
      space for the number to fit in to.
     \end{minipage}
  \end{equation}

* Experimental
The usual experimental details should appear here. This could include a table,
which can be referenced as Table \ref{tbl:example} or [[tbl:example]]. Notice that the caption is
positioned at the top of the table.

#+NAME: tbl:example
#+CAPTION: An example table.
#+ATTR_LATEX: :align ll 
| Header one  | Header two  |
|-------------+-------------|
| Entry one   | Entry two   |
| Entry three | Entry four  |
| Entry five  | Entry five  |
| Entry seven | Entry eight |
|-------------+-------------|

Adding notes to tables can be complicated. Perhaps the easiest method is to
generate these using the basic \texttt{\textbackslash textsuperscript} and
\texttt{\textbackslash emph} macros, as illustrated (Table \ref{tbl:notes} or [[tbl:notes]]).

#+NAME: tbl:notes
#+CAPTION: A table with notes.
#+ATTR_LATEX: :align ll 
|-------------------------------------------------------------------+------------|
| Header one                                                        | Header two |
| Entry one^{*[a]*}                                                      | Entry two  |
| Entry three^{*[b]*}                                                    | Entry four |
|-------------------------------------------------------------------+------------|
| \footnotesize{[a] Some text};  \footnotesize{[b] Some more text}. |            |


The example file also loads the optional \textsf{chemformula} and =mhchem= packages, so that formulas are easy to input =\ce{H2SO4}= gives \ce{H2SO4}. The two have similar syntax but authors may prefer one or the other.

The use of new commands should be limited to simple things which will not interfere with the production process. For example, ={mycommand}= has been defined in this example, to give italic, mono-spaced text:
\mycommand{some text}.

* Acknowledgment

Please use ``The authors thank \ldots'' rather than ``The authors would like to
thank \ldots''.

* Supporting information
A listing of the contents of each file supplied as Supporting Information
should be included. For instructions on what should be included in the
Supporting Information as well as how to prepare this material for
publications, refer to the journal's Instructions for Authors.

The following files are available free of charge.
#+begin_src latex

  \begin{itemize}
    \item Filename-1: brief description
    \item Filename-2: brief description
  \end{itemize}

#+end_src


#+begin_src latex

  \printbibliography

#+end_src


\clearpage

* Entry for the Table of Contents
#+latex: \singlespacing

#+begin_src latex

\rule{0.05in}{1.75in}%
\begin{minipage}[b][1.75in]{3.25in}
  \sffamily
  \frenchspacing
  Some journals require a graphical entry for the Table of Contents. This
  should be laid out ``print ready'' so that the sizing of the text is correct.

  The space available depends on the journal: J. Am. Chem. Soc. allows 3.25 in
  by 1.75 in and requires sanserif text. Some journals want different sizes:
  you can easily adjust here.
  
  The two rules either side of the content are there to help judge the height
  of your material: they may be deleted once not required.
  
\end{minipage}%
\rule{0.05in}{1.75in}

#+end_src



